name: Build CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Render PDF HTML with dev-ats theme
        run: npx resumed render resume.JSON --theme jsonresume-theme-dev-ats --output docs/temp-pdf.html

      - name: Generate PDF CV
        run: node generate-pdf.js
        # Ensure generate-pdf.js is updated to use docs/temp-pdf.html

      - name: Render final HTML CV with stackoverflow theme
        run: npx resumed render resume.JSON --theme jsonresume-theme-stackoverflow --output docs/index.html
