name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build and Commit CV"]
    types: [completed]

permissions:
  contents: write

jobs:
  deploy:
    # Only run if the build concluded successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs         # folder that has index.html, etc.
          publish_branch: gh-pages  # default is gh-pages, but be explicit
